"""
Prometheus Metrics Configuration
Advanced metrics collection for monitoring and observability
"""

from prometheus_client import Counter, Histogram, Gauge, Info
from prometheus_client import CollectorRegistry, generate_latest, CONTENT_TYPE_LATEST
from fastapi import Response
import time
from typing import Callable
from functools import wraps
import logging

logger = logging.getLogger(__name__)

# Create custom registry
registry = CollectorRegistry()

# ============================================================
# Application Metrics
# ============================================================

# Request metrics
http_requests_total = Counter(
    'http_requests_total',
    'Total HTTP requests',
    ['method', 'endpoint', 'status'],
    registry=registry
)

http_request_duration_seconds = Histogram(
    'http_request_duration_seconds',
    'HTTP request duration in seconds',
    ['method', 'endpoint'],
    buckets=(0.01, 0.05, 0.1, 0.5, 1.0, 2.0, 5.0, 10.0),
    registry=registry
)

# ============================================================
# RAG Q&A Metrics
# ============================================================

qa_requests_total = Counter(
    'qa_requests_total',
    'Total Q&A requests',
    ['service_type'],  # sync or async
    registry=registry
)

qa_request_duration_seconds = Histogram(
    'qa_request_duration_seconds',
    'Q&A request duration in seconds',
    ['service_type'],
    buckets=(0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0),
    registry=registry
)

qa_confidence_score = Histogram(
    'qa_confidence_score',
    'Q&A confidence score distribution',
    buckets=(0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0),
    registry=registry
)

# ============================================================
# Vector DB Metrics
# ============================================================

qdrant_search_duration_seconds = Histogram(
    'qdrant_search_duration_seconds',
    'Qdrant search duration in seconds',
    buckets=(0.01, 0.05, 0.1, 0.5, 1.0, 2.0),
    registry=registry
)

qdrant_search_results_count = Histogram(
    'qdrant_search_results_count',
    'Number of results from Qdrant search',
    buckets=(0, 1, 3, 5, 10, 20, 50, 100),
    registry=registry
)

# ============================================================
# LLM Metrics
# ============================================================

llm_requests_total = Counter(
    'llm_requests_total',
    'Total LLM requests',
    ['model', 'status'],  # status: success, error, timeout
    registry=registry
)

llm_request_duration_seconds = Histogram(
    'llm_request_duration_seconds',
    'LLM request duration in seconds',
    ['model'],
    buckets=(0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0),
    registry=registry
)

llm_tokens_generated = Histogram(
    'llm_tokens_generated',
    'Number of tokens generated by LLM',
    ['model'],
    buckets=(10, 50, 100, 200, 500, 1000, 2000),
    registry=registry
)

# ============================================================
# Embedding Metrics
# ============================================================

embedding_generation_duration_seconds = Histogram(
    'embedding_generation_duration_seconds',
    'Embedding generation duration in seconds',
    buckets=(0.01, 0.05, 0.1, 0.5, 1.0),
    registry=registry
)

# ============================================================
# System Metrics
# ============================================================

active_requests = Gauge(
    'active_requests',
    'Number of active requests',
    registry=registry
)

connection_pool_size = Gauge(
    'connection_pool_size',
    'Size of HTTP connection pool',
    ['pool_type'],  # ollama, qdrant
    registry=registry
)

# ============================================================
# Error Metrics
# ============================================================

errors_total = Counter(
    'errors_total',
    'Total errors',
    ['error_type', 'component'],
    registry=registry
)

# ============================================================
# Application Info
# ============================================================

app_info = Info(
    'rag_enterprise',
    'RAG Enterprise application information',
    registry=registry
)

app_info.info({
    'version': '2.0.0',
    'environment': 'production',
    'features': 'async_qa,batch_processing,connection_pooling'
})

# ============================================================
# Decorator Functions
# ============================================================

def track_qa_request(service_type: str = "sync"):
    """
    Decorator to track Q&A request metrics

    Usage:
        @track_qa_request(service_type="async")
        async def answer_question(...):
            ...
    """
    def decorator(func: Callable):
        @wraps(func)
        async def async_wrapper(*args, **kwargs):
            qa_requests_total.labels(service_type=service_type).inc()

            start_time = time.time()
            try:
                result = await func(*args, **kwargs)
                duration = time.time() - start_time
                qa_request_duration_seconds.labels(service_type=service_type).observe(duration)

                # Track confidence if available
                if isinstance(result, dict) and 'confidence' in result:
                    qa_confidence_score.observe(result['confidence'])

                return result
            except Exception as e:
                errors_total.labels(
                    error_type=type(e).__name__,
                    component='qa_service'
                ).inc()
                raise

        @wraps(func)
        def sync_wrapper(*args, **kwargs):
            qa_requests_total.labels(service_type=service_type).inc()

            start_time = time.time()
            try:
                result = func(*args, **kwargs)
                duration = time.time() - start_time
                qa_request_duration_seconds.labels(service_type=service_type).observe(duration)

                # Track confidence if available
                if isinstance(result, dict) and 'confidence' in result:
                    qa_confidence_score.observe(result['confidence'])

                return result
            except Exception as e:
                errors_total.labels(
                    error_type=type(e).__name__,
                    component='qa_service'
                ).inc()
                raise

        # Return appropriate wrapper based on function type
        import asyncio
        if asyncio.iscoroutinefunction(func):
            return async_wrapper
        return sync_wrapper

    return decorator


def track_qdrant_search():
    """Decorator to track Qdrant search metrics"""
    def decorator(func: Callable):
        @wraps(func)
        async def async_wrapper(*args, **kwargs):
            start_time = time.time()
            try:
                results = await func(*args, **kwargs)
                duration = time.time() - start_time
                qdrant_search_duration_seconds.observe(duration)

                # Track result count
                if isinstance(results, list):
                    qdrant_search_results_count.observe(len(results))

                return results
            except Exception as e:
                errors_total.labels(
                    error_type=type(e).__name__,
                    component='qdrant'
                ).inc()
                raise

        return async_wrapper

    return decorator


def track_llm_request(model: str):
    """Decorator to track LLM request metrics"""
    def decorator(func: Callable):
        @wraps(func)
        async def async_wrapper(*args, **kwargs):
            start_time = time.time()
            try:
                result = await func(*args, **kwargs)
                duration = time.time() - start_time

                llm_request_duration_seconds.labels(model=model).observe(duration)
                llm_requests_total.labels(model=model, status='success').inc()

                # Track tokens if available
                if isinstance(result, dict) and 'tokens' in result:
                    llm_tokens_generated.labels(model=model).observe(result['tokens'])

                return result
            except Exception as e:
                llm_requests_total.labels(model=model, status='error').inc()
                errors_total.labels(
                    error_type=type(e).__name__,
                    component='llm'
                ).inc()
                raise

        return async_wrapper

    return decorator


# ============================================================
# Metrics Endpoint
# ============================================================

def metrics_endpoint() -> Response:
    """
    Generate Prometheus metrics endpoint response

    Usage in FastAPI:
        @app.get("/metrics")
        def get_metrics():
            return metrics_endpoint()
    """
    metrics_data = generate_latest(registry)
    return Response(
        content=metrics_data,
        media_type=CONTENT_TYPE_LATEST
    )


# ============================================================
# Helper Functions
# ============================================================

def increment_active_requests():
    """Increment active requests counter"""
    active_requests.inc()


def decrement_active_requests():
    """Decrement active requests counter"""
    active_requests.dec()


def set_connection_pool_size(pool_type: str, size: int):
    """Set connection pool size gauge"""
    connection_pool_size.labels(pool_type=pool_type).set(size)


def record_embedding_duration(duration: float):
    """Record embedding generation duration"""
    embedding_generation_duration_seconds.observe(duration)


def record_error(error_type: str, component: str):
    """Record an error"""
    errors_total.labels(error_type=error_type, component=component).inc()


logger.info("✅ Prometheus metrics initialized")
